### ISSUE TITLE
[Suggestion] Making an Option for enabling Players to get all items

### ISSUE THREAD

**Issue by Sparky7198** [TestRunnerSRL/bizhawk-co-op#12]
To be honest its kinda Frustating That you have to stay close to each other in,more Specifically Metroid Zero Mission to get all the items so it would be nice to have an option that allows Both/All the Players to get all the Items and erasing them Afterwards to other people

**Comment by TestRunnerSRL** [comment]
We talked about and resolved this separately, so I'm going to close this
