### ISSUE TITLE
Problems Connecting with Another player on same network

### ISSUE THREAD

**Issue by zahuranecs** [TestRunnerSRL/bizhawk-co-op#16]
Is there any way I can run the bizhawk to another player on the same network? I've tried "localhost" as IP and we've tried both of our IPv4 addresses.  We can connect to the rooms in lua, but nothing in the games syncs with the other client.
-I have personally confirmed that everything is the same... (Same seeds, bizhawk version, and randomizer version.)
-Have also gone through all the Hamachi firewall settings [here](https://help.logmein.com/articles/en_US/FAQ/Resolving-Hamachi-Request-Timed-Out) and disabled the firewall on both pcs and they are pinging each other just fine...
-Both PCs are running Windows 10
-If you need any more info, please let me know

**Comment by TestRunnerSRL** [comment]
So you're able to connect but the items aren't being sent. This is likely a version error problem. The latest bizhawk co-op scripts only work on seeds from my latest OoT dev branch, so if you are running a 3.0 seed, replace bizhawk-co-op/ramcontroller/Ocarina of Time.lua with this file: https://github.com/TestRunnerSRL/bizhawk-co-op/raw/9e73e90eae6d5ef82cca96a9f3e6a235abbaf906/bizhawk-co-op/ramcontroller/Ocarina%20of%20Time.lua

**Comment by zahuranecs** [comment]
Awesome, **works now**!  Tried so many different things with no luck, but that fixed it! You're the best!
