### ISSUE TITLE
Games got out of sync

### ISSUE THREAD

**Issue by donb1991** [TestRunnerSRL/bizhawk-co-op#19]
Had an issue where one player got a key item for other. But we got disconnected from the room. We we got reconnected the item never popped. Tried both of us saving and restart the game. With no luck.

Did get this error in the lue console after we reconnected.

```
Configuration consistency check failed: Bad hash
[07:21:34] You are not both using the same sync code (perhaps one of you is using an older version?)
[07:21:34] Make sure your sync code is the same and try again. 
```

**Comment by TestRunnerSRL** [comment]
i mean that error message means you never connected because your code is not the same. Try redownloading it. Also if you are on 3.0 please refer to #16
