### ISSUE TITLE
Re-connecting After Accidentatly Closing the Lua instead of Leaving the room Cleanly

### ISSUE THREAD

**Issue by Sparky7198** [TestRunnerSRL/bizhawk-co-op#7]
What can i do to use the Same Username to create another room? its been a few days already and the Connection is aparently still "up" (My Usernames that i used are Felipe,Sparky and Sparky7198)

**Comment by TestRunnerSRL** [comment]
If you create a new room with the same name and password, then it'll replace it. If you then want to change your password, then close room to clear it cleanly, and you can then make a new room with any password.

**Comment by Sparky7198** [comment]
I tried to do that but it just gives me an error when i try to create a room with the same name and password

**Comment by Duskbatty** [comment]
I have the same issue, took a while to figure out why it was happening, but now whenever I make a room using the username I usually go with, it just says this:

[00:27:53] Created server on port (Insert port here)
[00:27:53] Error creating room [Code: 401]
[00:27:53] Error closing room [Code: 401]
[00:27:53] Server closed.
